name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to EC2 via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "~/app"

      - name: SSH into EC2 and build & deploy Docker
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app
            docker tag node-app node-app:rollback || true
            docker build -t node-app .
            docker stop node-app || true
            docker rm node-app || true
            docker run -d -p 80:3000 --name node-app node-app

      - name: Health check on /status
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            for i in {1..5}; do
              if curl -f http://localhost:80/status; then
                echo "✅ Application is healthy"
                exit 0
              fi
              echo "Attempt $i: not ready..."
              sleep 10
            done
            echo "❌ Health check failed"
            exit 1

      - name: Rollback on failure
        if: failure()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🔄 Rolling back to previous version"
            docker stop node-app || true
            docker rm node-app || true
            docker run -d -p 80:3000 --name node-app node-app:rollback
            echo "✅ Rollback complete"

      - name: Notify on failure
        if: failure()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🚨 Deployment failed—logs:"
            docker logs node-app
