name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2 via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 16.16.205.36
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "~/app"

      - name: SSH into EC2 and run Docker
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 16.16.205.36
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app
            docker build -t node-app .
            docker stop node-app || true
            docker rm node-app || true
            docker run -d -p 80:3000 --name node-app node-app
